### ISSUE TITLE
Merge distro-specific patches upstream

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot#171]
# Notable Forks

- [ ] [Debian](https://packages.debian.org/source/sid/proot)
- [ ] [Termux](https://github.com/termux/proot) (See: https://github.com/termux/proot/issues/22)
  - [ ] [Add support for Linux >= 4.8](https://github.com/termux/proot/commit/47138da843bbfcea2273a11ce9d83b40031465bf) Contains Android-specific functionality
- [ ] [UDocker](https://github.com/indigo-dc/udocker) (See: https://github.com/jorge-lip/PRoot/tree/udocker-1.1.1)
  - [ ] [proot_event.patch](https://github.com/indigo-dc/udocker/blob/master/utils/proot_event.patch) (See: https://github.com/proot-me/proot/issues/106#issuecomment-472225613) Slightly different than version submitted in https://github.com/proot-me/proot/pull/130
  - [x] [proot_temp.patch](https://github.com/indigo-dc/udocker/blob/master/utils/proot_temp.patch)
- [ ] [proot-android.patch](https://github.com/pelya/debian-noroot/blob/master/proot-android.patch), (See: https://github.com/proot-me/proot/issues/93). NEEDS WORK
- [x] [openmole](https://github.com/openmole/PRoot)
  - [x] [Fix seccomp filters](https://github.com/openmole/PRoot/commit/10119a1f1fd7dea012464ae176c2b5fc3eb18928)

This is an attempt to find all of the most popular offshoots of PRoot and merge any helpful patches found. If you know if any, please add them below in a comment.
