### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot#207]
- [x] Mentor organizations must run an active open source or free software project.
- [x] Have produced and released software under an OSI approved license.
- [x] Must not be based in a country currently embargoed by the United States.

Source: https://summerofcode.withgoogle.com/terms/org

See also: https://google.github.io/gsocguides/mentor/notes-for-first-year-organizations

**Comment by oxr463** [comment]
Another alternative, is to present PRoot as a possible project for an existing organization such as one of the following:

- [ ] [Debian](https://summerofcode.withgoogle.com/archive/2019/organizations/4816120068964352/)
- [ ] [Fedora](https://summerofcode.withgoogle.com/archive/2019/organizations/6739854375780352/)
- [ ] [Gentoo](https://summerofcode.withgoogle.com/archive/2019/organizations/4508206280212480/)
- [ ] [GNU](https://summerofcode.withgoogle.com/archive/2019/organizations/5352439094444032/)
